name: Go Lint

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'The working directory to run the linter'
        required: true
        default: './webapp/golang'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: stable
        cache-dependency-path: ${{ inputs.working-directory }}/go.sum

    - run: cd ${{ inputs.working-directory }} && go mod tidy

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        only-new-issues: true
        working-directory: ${{ inputs.working-directory }}
        args: --timeout=10m
