name: Node.js Syntax Checker

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: 'webapp/node までのパス'
        required: false
        default: './webapp/node'

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: latest

    # node --check で構文チェックのみ行う
    - run: |
        find ${{ inputs.working-directory }} -name "*.js" | while read -r file; do
          echo "Checking $file"
          if ! node --check "$file"; then
            echo "Syntax error in $file"
            exit 1
          fi
        done
