name: Go Linter Caller

on:
  push:
    paths:
      - '**/*.go'

permissions:
  contents: read
  pull-requests: read

jobs:
  call-linter:
    uses: ./.github/workflows/golang.yml
    with:
      working-directory: './webapp/golang'
      golangci-config: './.golangci.yml'
