name: Go Linter Caller

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  call-linter:
    uses: ./.github/workflows/golang.yml
    with:
      working-directory: './webapp/golang'
      golangci-config: '.golangci.yml'
