name: Node Check Caller

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  check:
    uses: ./.github/workflows/node.yml
    with:
      working-directory: './webapp/node'
